/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on 30/05/2010, 14:39:11
 */
package concesionaria;

import java.util.Calendar;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author s
 */
public class GUI extends javax.swing.JFrame {

  Calculador calculadora = new Calculador();
//  Vector<TransporteCarga> v = (Vector)calculadora.getVectorCarga();
  String[] arreglo;
  
  /** Creates new form GUI */
  public GUI() {

    initComponents();

    String aaa ="aaa";
    //Puebla arriba a la derecha, las cajas con valores obtenidos de los archivos

    //--------- COMIENZA LLENADO DE CAJAS SUPERIORES ----------------

    //Usa un metodo publico de tipo getter para recibir una copia del diccionario
    HashMap p = calculadora.getDiccionario_vehiculos();

    //Saca del diccionario el primer valor
    Double unDouble = (Double) p.get("transporte-impuestos");//ojo q es Double
    //Lo convierte en una Cadena
    String unString = Double.toString(unDouble);
    //...Para poder mostrarlo en una caja de texto
    Caja1.setText(unString);
    
    
    //Saca del diccionario el segundo valor
    unDouble = (Double) p.get("transporte-utilidades");//ojo q es Double
    //Lo convierte en una Cadena
    unString = Double.toString(unDouble);
    //...Para poder mostrarlo en una caja de texto
    Caja2.setText(unString);
    
    //Saca del diccionario el tercer valor
    unDouble = (Double) p.get("particulares-impuestos");//ojo q es Double

    //Lo convierte en una Cadena
    unString = Double.toString(unDouble);

    //...Para poder mostrarlo en una caja de texto
    Caja3.setText(unString);

    //Saca del diccionario el cuarto valor
    unDouble = (Double) p.get("particulares-utilidades");//ojo q es Double

    //Lo convierte en una Cadena
    unString = Double.toString(unDouble);

    //...Para poder mostrarlo en una caja de texto
    Caja4.setText(unString);

    //Saca del diccionario el quinto valor
    unDouble = (Double) p.get("carga-impuestos");//ojo q es Double

    //Lo convierte en una Cadena
    unString = Double.toString(unDouble);

    //...Para poder mostrarlo en una caja de texto
    Caja5.setText(unString);

    //Saca del diccionario el sexto valor
    unDouble = (Double) p.get("carga-utilidades");//ojo q es Double

    //Lo convierte en una Cadena
    unString = Double.toString(unDouble);

    //...Para poder mostrarlo en una caja de texto
    Caja6.setText(unString);

    //--------- FIN LLENADO DE CAJAS SUPERIORES ----------------



    //~~~~~~~ COMIENZA LLENADO DE CAJA DE COEFICIENTE ~~~~~~~~~~
    //Usa un metodo publico de tipo getter para recibir una copia del diccionario
    HashMap q = calculadora.getDiccionario_coeficientes();

    //Buscando año en curso
    Calendar ahora = Calendar.getInstance();
    Integer anio = ahora.get(Calendar.YEAR);

    //Seteando año en curso sobre el Label "Anio"
    Anio.setText(anio.toString());

    //Buscando en el diccionario q, el coeficiente. Para lograrlo, buscamos entre
    //las llaves, una que se denomine "2010" (como cadena, cuidado!)

     //JOptionPane.showMessageDialog(null, );
    Integer coeficiente = (Integer) q.get(2010);


    //Seteando coeficiente que corresponde al año en curso
    Coeficiente.setText(coeficiente.toString());

/*
    //Saca del diccionario el primer valor
    Double otroDouble = (Double) p.get("transporte-impuestos");//ojo q es Double
    //Lo convierte en una Cadena
    String unString = Double.toString(unDouble);
    //...Para poder mostrarlo en una caja de texto
    Caja1.setText(unString);
  */

    //~~~~~~~ FIN LLENADO DE CAJA DE COEFICIENTE ~~~~~~~~~~


    //######## COMIENZA LLENADO DE JLists con Vehiculos ###############

//    Vector<TransporteCarga> v = (Vector)calculadora.getVectorCarga();
   


    //######## FIN LLENADO DE JLists con Vehiculos ####################


    this.setVisible(true);
  }//Constructor

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")



    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Caja1 = new javax.swing.JTextField();
        Caja3 = new javax.swing.JTextField();
        Caja2 = new javax.swing.JTextField();
        Caja4 = new javax.swing.JTextField();
        Caja5 = new javax.swing.JTextField();
        Caja6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Anio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Coeficiente = new javax.swing.JLabel();
        BotonGUITransporte = new javax.swing.JButton();
        BotonGUIParticular = new javax.swing.JButton();
        BotonGUICarga = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CajaValorReajuste = new javax.swing.JTextField();
        CajaCuotas = new javax.swing.JTextField();
        BotonCotizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        Lista3 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Valores generales");

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Impuesto");

        jLabel4.setText("Utilidad");

        jLabel7.setText("Coeficiente correspondiente al año en curso:");

        Anio.setText("jLabel8");

        jLabel8.setText("->");

        Coeficiente.setText("jLabel9");

        BotonGUITransporte.setText("Transporte");
        BotonGUITransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGUITransporteActionPerformed(evt);
            }
        });

        BotonGUIParticular.setText("Particular");

        BotonGUICarga.setText("Carga");

        jLabel2.setText("Escoja vehiculo de nuestro stock:");

        jLabel5.setText("Valor de Reajuste");

        jLabel6.setText("Cuotas");

        BotonCotizar.setText("Cotizar");

        Lista1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Lista1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Lista1);

        Lista2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Lista2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(Lista2);

        Lista3.setModel(new javax.swing.AbstractListModel() {

            Stock unStock = new Stock();
            Vector v = unStock.getVectorCarga();

            /*
            for (Integer y = 0; y < v.size(); y++) {
                TransporteCarga aux = (TransporteCarga) v.elementAt(y);
                //String s = (String) aux.getMarca();
                //System.out.println(s);

            } */

            /*
            TransporteCarga aux = (TransporteCarga) v.elementAt(0);
            String s = (String) aux.getMarca();
            String aaa="aaab";

            String[] strings = { aaa, s, "Item 3", "Item 4", "Item 5" };
            */
            String[] strings = unStock.getArregloCarga();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Lista3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(Lista3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonGUITransporte)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Caja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Caja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Anio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Coeficiente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonGUIParticular)
                        .addGap(34, 34, 34)
                        .addComponent(Caja3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Caja4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CajaCuotas, 0, 0, Short.MAX_VALUE)
                            .addComponent(CajaValorReajuste, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonCotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(BotonGUICarga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Caja5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Caja6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(480, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BotonGUICarga, BotonGUIParticular, BotonGUITransporte, Caja1, Caja2, Caja3, Caja4, Caja5, Caja6, jButton1, jLabel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Anio)
                            .addComponent(jLabel8)
                            .addComponent(Coeficiente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Caja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Caja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotonGUITransporte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonCotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CajaValorReajuste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CajaCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Caja5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Caja6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(BotonGUICarga))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonGUIParticular)
                        .addComponent(Caja3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Caja4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BotonGUICarga, BotonGUIParticular, BotonGUITransporte, Caja1, Caja2, Caja3, Caja4, Caja5, Caja6});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      //Un HashMap auxiliar donde guardar todas las cajas de texto
      HashMap aux = new HashMap();

      //Rellenando el diccionario auxiliar...
      aux.put("transporte-impuestos", new Double (Caja1.getText() ) );
      aux.put("transporte-utilidades", new Double (Caja2.getText() ) );
      aux.put("particulares-impuestos", new Double (Caja3.getText() ) );
      aux.put("particulares-utilidades", new Double (Caja4.getText() ) );
      aux.put("carga-impuestos", new Double (Caja5.getText() ) );
      aux.put("carga-utilidades", new Double (Caja6.getText() ) );

      calculadora.setDiccionario_vehiculos(aux);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotonGUITransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGUITransporteActionPerformed
      /*GUITransporte ListaT = new GUITransporte();
      JOptionPane.showMessageDialog(null, "Valor seleccionado" + ListaT.getTransporteSeleccionado());
       * 
       */
      //CajaVehiculoSeleccionado.setText(ListaT.getTransporteSeleccionado().toString());
    }//GEN-LAST:event_BotonGUITransporteActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new GUI().setVisible(true);
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anio;
    private javax.swing.JButton BotonCotizar;
    private javax.swing.JButton BotonGUICarga;
    private javax.swing.JButton BotonGUIParticular;
    private javax.swing.JButton BotonGUITransporte;
    private javax.swing.JTextField Caja1;
    private javax.swing.JTextField Caja2;
    private javax.swing.JTextField Caja3;
    private javax.swing.JTextField Caja4;
    private javax.swing.JTextField Caja5;
    private javax.swing.JTextField Caja6;
    private javax.swing.JTextField CajaCuotas;
    private javax.swing.JTextField CajaValorReajuste;
    private javax.swing.JLabel Coeficiente;
    private javax.swing.JList Lista1;
    private javax.swing.JList Lista2;
    private javax.swing.JList Lista3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
